### ISSUE TITLE
[Hacktoberfest Seoul] Add new technologies to `README`

### ISSUE THREAD

**Issue by behzodhalil** [getspherelabs/anypass-kmp#122]

**Comment by behzodhalil** [comment]
- AssertK
- Konsist
- Lyricist
- Uri-kmp
- Test-logger
- CameraX
- MLKit

**Comment by cloudchamb3r** [comment]
@behzodhalil I'll take this issue

**Comment by behzodhalil** [comment]
https://github.com/radarsh/gradle-test-logger-plugin
