### ISSUE TITLE
Use `fingerprint` feature in account module

### ISSUE THREAD

**Issue by behzodhalil** [getspherelabs/anypass-kmp#72]

**Comment by rooparsh** [comment]
Hey @behzodhalil , is this feature currently owned by anyone/you ? If not, let me know if I can help contribute ? I have done something similar in one of my past projects.
TIA

**Comment by behzodhalil** [comment]
Hey @rooparsh!

This feature already added, you can check it out this module `manager/biometry`. Now these issues are available to contribute:

- https://github.com/getspherelabs/anypass-kmp/issues/73
- https://github.com/getspherelabs/anypass-kmp/issues/46
- https://github.com/getspherelabs/anypass-kmp/issues/85
- https://github.com/getspherelabs/anypass-kmp/issues/86
- https://github.com/getspherelabs/anypass-kmp/issues/92
- https://github.com/getspherelabs/anypass-kmp/issues/37
- https://github.com/getspherelabs/anypass-kmp/issues/91
