### ISSUE TITLE
Add validation check when add new passwords

### ISSUE THREAD

**Issue by behzodhalil** [getspherelabs/anypass-kmp#84]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Kardelio** [comment]
OOoooooooooo if its not already assigned could I possibly jump on this ticket?
No worries if not just looks interesting!

**Comment by Kardelio** [comment]
as in the work for this issue is already done? or just the validation function/method is available to be used in this issue?

**Comment by behzodhalil** [comment]
Hey, @Kardelio 

The validation module is available to be used in this issue. I didn't add this to `addNewPassword` domain and presentation modules. For this issue, we need to add logics to the domain and presentation modules. 

Thanks
