### ISSUE TITLE
Add `In-app updates` to Android

### ISSUE THREAD

**Issue by behzodhalil** [getspherelabs/anypass-kmp#92]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by behzodhalil** [comment]
FYI: iOS does not have the auto update feature that Android has

**Comment by alibardide5124** [comment]
Is this require google play panel, or I just need to code the app? If it doesn't need google play, I'd like to take it :)

**Comment by behzodhalil** [comment]
Hey, @alibardide5124 ! Thanks for your interest our project!

Just need to add logic (in app updates) to our app.

**Comment by alibardide5124** [comment]
Thanks, @behzodhalil. I'm on it.

Since I didn't work on multiplatform projects, this would be a good example to look at :)

**Comment by alibardide5124** [comment]
By the way, I didn't see any release or download link. Where can I download APK file?

**Comment by alibardide5124** [comment]
Hi. I've implemented update logic to app. It checks for update and finish app if user don't update. This was a project that requires security, so I assumed the user should immediately update for safety.

However, there was a catch... You see I didn't work with multimodule Gradle dependency in apps (Like your app that has navigation, AdMob, etc. folders in root directory) And I got an error as I opened project:

A problem occurred configuring project ':resource'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':resource:classpath'.
      > Failed to calculate the value of task ':build-logic:convention:compileJava' property 'javaCompiler'.
         > No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
            > No locally installed toolchains match (see https://docs.gradle.org/8.0/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0/userguide/toolchains.html#sub:download_repositories).

It's related to your resource module. I spent a few hours, but I couldn't figure it out. So I just implemented logic in MainActivity.kt and push it. I pretty sure it works. Just test it from play console. 

And greatly sorry for this :(

**Comment by behzodhalil** [comment]
@alibardide5124 I'm pleased to see that you've implemented the "in-app update" feature. I've reviewed to your code.

Additionally, we are following the `git flow` branching strategy. For running `CI/CD`, please make a request to merge into the `develop` branch.

Thanks!

**Comment by behzodhalil** [comment]
@alibardide5124 
FYI: Now, I'm working with this issue #94. After finishing, `gradle` files will change.

**Comment by alibardide5124** [comment]
Hi @behzodhalil. I just made some changes to code, and you can see diff here:
https://github.com/getspherelabs/anypass-kmp/compare/main...alibardide5124:anypass-kmp:fix_issue_%2392_in_app_update

If you could, please check it out and tell me if I missed anything. I realized that I can't work on a multiplatform project with a Windows device, so I wrote logic in another project and implemented it on this project. 

You mentioned earlier that I missed an important part of the in-app update. I checked my code and I didn't see what's wrong. Can you please tell me what I missed?

**Comment by behzodhalil** [comment]
Hey, @alibardide5124!

Sorry for late response! I'll review right now your PR.
